site_name: AstroFetch
site_description: PyTorch-friendly, ML-ready access to planetary science data, starting with the Moon.
repo_url: https://github.com/TechnicToms/AstroFetch
repo_name: TechnicToms/AstroFetch

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Roadmap: roadmap.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
